server:
  port: 9527
spring:
  application:
    name: cloud-zuul-gateway
#Eureka的配置，服务注册到那里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-zuul-gateway-9527
    prefer-ip-address: true #改为true表示显示IP
#配置info信息
info:
  app.name: cloud-zuul-gateway-9527
  company.name: jacklinsir.com

#配置Zuul路由网关
zuul:
  prefix: /jacklin
  ignored-services: "*"
  routes:
    myemp.serviceId: cloud-provider-emp
    myemp.path: /myemp/**

